INSERT INTO categoria (`id`,`nombre`) VALUES (1,'Baseplates');
INSERT INTO categoria (`id`,`nombre`) VALUES (2,'Bricks Printed');
INSERT INTO categoria (`id`,`nombre`) VALUES (3,'Bricks Sloped');
INSERT INTO categoria (`id`,`nombre`) VALUES (4,'Duplo, Quatro and Primo');
INSERT INTO categoria (`id`,`nombre`) VALUES (5,'Bricks Special');
INSERT INTO categoria (`id`,`nombre`) VALUES (6,'Bricks Wedged');
INSERT INTO categoria (`id`,`nombre`) VALUES (7,'Containers');
INSERT INTO categoria (`id`,`nombre`) VALUES (8,'Technic Bricks');
INSERT INTO categoria (`id`,`nombre`) VALUES (9,'Plates Special');
INSERT INTO categoria (`id`,`nombre`) VALUES (10,'Tiles Printed');
INSERT INTO categoria (`id`,`nombre`) VALUES (11,'Bricks');
INSERT INTO categoria (`id`,`nombre`) VALUES (12,'Technic Connectors');
INSERT INTO categoria (`id`,`nombre`) VALUES (13,'Minifigs');
INSERT INTO categoria (`id`,`nombre`) VALUES (14,'Plates');
INSERT INTO categoria (`id`,`nombre`) VALUES (15,'Tiles Special');
INSERT INTO categoria (`id`,`nombre`) VALUES (16,'Windows and Doors');
INSERT INTO categoria (`id`,`nombre`) VALUES (17,'Non-LEGO');
INSERT INTO categoria (`id`,`nombre`) VALUES (18,'Hinges, Arms and Turntables');
INSERT INTO categoria (`id`,`nombre`) VALUES (19,'Tiles');
INSERT INTO categoria (`id`,`nombre`) VALUES (20,'Bricks Round and Cones');
INSERT INTO categoria (`id`,`nombre`) VALUES (21,'Plates Round and Dishes');
INSERT INTO categoria (`id`,`nombre`) VALUES (22,'Pneumatics');
INSERT INTO categoria (`id`,`nombre`) VALUES (23,'Panels');
INSERT INTO categoria (`id`,`nombre`) VALUES (24,'Other');
INSERT INTO categoria (`id`,`nombre`) VALUES (25,'Technic Steering, Suspension and Engine');
INSERT INTO categoria (`id`,`nombre`) VALUES (26,'Technic Special');
INSERT INTO categoria (`id`,`nombre`) VALUES (27,'Minifig Accessories');
INSERT INTO categoria (`id`,`nombre`) VALUES (28,'Plants and Animals');
INSERT INTO categoria (`id`,`nombre`) VALUES (29,'Wheels and Tyres');
INSERT INTO categoria (`id`,`nombre`) VALUES (30,'Tubes and Hoses');
INSERT INTO categoria (`id`,`nombre`) VALUES (31,'String, Bands and Reels');
INSERT INTO categoria (`id`,`nombre`) VALUES (32,'Bars, Ladders and Fences');
INSERT INTO categoria (`id`,`nombre`) VALUES (33,'Rock');
INSERT INTO categoria (`id`,`nombre`) VALUES (34,'Supports, Girders and Cranes');
INSERT INTO categoria (`id`,`nombre`) VALUES (35,'Transportation - Sea and Air');
INSERT INTO categoria (`id`,`nombre`) VALUES (36,'Transportation - Land');
INSERT INTO categoria (`id`,`nombre`) VALUES (37,'Bricks Curved');
INSERT INTO categoria (`id`,`nombre`) VALUES (38,'Flags, Signs, Plastics and Cloth');
INSERT INTO categoria (`id`,`nombre`) VALUES (39,'Magnets and Holders');
INSERT INTO categoria (`id`,`nombre`) VALUES (40,'Technic Panels');
INSERT INTO categoria (`id`,`nombre`) VALUES (41,'Bionicle, Hero Factory and Constraction');
INSERT INTO categoria (`id`,`nombre`) VALUES (42,'Belville, Scala and Fabuland');
INSERT INTO categoria (`id`,`nombre`) VALUES (43,'Znap');
INSERT INTO categoria (`id`,`nombre`) VALUES (44,'Mechanical');
INSERT INTO categoria (`id`,`nombre`) VALUES (45,'Power Functions, Mindstorms and Electric');
INSERT INTO categoria (`id`,`nombre`) VALUES (46,'Technic Axles');
INSERT INTO categoria (`id`,`nombre`) VALUES (47,'Windscreens and Fuselage');
INSERT INTO categoria (`id`,`nombre`) VALUES (48,'Clikits');
INSERT INTO categoria (`id`,`nombre`) VALUES (49,'Plates Angled');
INSERT INTO categoria (`id`,`nombre`) VALUES (50,'HO Scale');
INSERT INTO categoria (`id`,`nombre`) VALUES (51,'Technic Beams');
INSERT INTO categoria (`id`,`nombre`) VALUES (52,'Technic Gears');
INSERT INTO categoria (`id`,`nombre`) VALUES (53,'Technic Pins');
INSERT INTO categoria (`id`,`nombre`) VALUES (54,'Technic Bushes');
INSERT INTO categoria (`id`,`nombre`) VALUES (55,'Technic Beams Special');
INSERT INTO categoria (`id`,`nombre`) VALUES (56,'Tools');
INSERT INTO categoria (`id`,`nombre`) VALUES (57,'Non-Buildable Figures (Duplo, Fabuland, etc)');
