INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (0,'Black','05131D','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (1,'Blue','0055BF','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (2,'Green','237841','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (3,'Dark Turquoise','008F9B','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (4,'Red','C91A09','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (5,'Dark Pink','C870A0','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (6,'Brown','583927','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (7,'Light Gray','9BA19D','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (8,'Dark Gray','6D6E5C','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (9,'Light Blue','B4D2E3','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (10,'Bright Green','4B9F4A','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (11,'Light Turquoise','55A5AF','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (12,'Salmon','F2705E','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (13,'Pink','FC97AC','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (14,'Yellow','F2CD37','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (15,'White','FFFFFF','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (17,'Light Green','C2DAB8','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (18,'Light Yellow','FBE696','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (19,'Tan','E4CD9E','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (20,'Light Violet','C9CAE2','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (21,'Glow In Dark Opaque','D4D5C9','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (22,'Purple','81007B','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (23,'Dark Blue-Violet','2032B0','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (25,'Orange','FE8A18','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (26,'Magenta','923978','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (27,'Lime','BBE90B','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (28,'Dark Tan','958A73','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (29,'Bright Pink','E4ADC8','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (30,'Medium Lavender','AC78BA','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (31,'Lavender','E1D5ED','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (32,'Trans-Black IR Lens','635F52','t');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (33,'Trans-Dark Blue','0020A0','t');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (34,'Trans-Green','84B68D','t');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (35,'Trans-Bright Green','D9E4A7','t');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (36,'Trans-Red','C91A09','t');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (40,'Trans-Black','635F52','t');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (41,'Trans-Light Blue','AEEFEC','t');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (42,'Trans-Neon Green','F8F184','t');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (43,'Trans-Very Lt Blue','C1DFF0','t');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (45,'Trans-Dark Pink','DF6695','t');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (46,'Trans-Yellow','F5CD2F','t');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (47,'Trans-Clear','FCFCFC','t');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (52,'Trans-Purple','A5A5CB','t');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (54,'Trans-Neon Yellow','DAB000','t');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (57,'Trans-Neon Orange','FF800D','t');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (60,'Chrome Antique Brass','645A4C','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (61,'Chrome Blue','6C96BF','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (62,'Chrome Green','3CB371','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (63,'Chrome Pink','AA4D8E','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (64,'Chrome Black','1B2A34','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (68,'Very Light Orange','F3CF9B','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (69,'Light Purple','CD6298','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (70,'Reddish Brown','582A12','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (71,'Light Bluish Gray','A0A5A9','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (72,'Dark Bluish Gray','6C6E68','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (73,'Medium Blue','5A93DB','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (74,'Medium Green','73DCA1','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (75,'Speckle Black-Copper','000000','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (76,'Speckle DBGray-Silver','635F61','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (77,'Light Pink','FECCCF','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (78,'Light Flesh','F6D7B3','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (79,'Milky White','FFFFFF','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (80,'Metallic Silver','A5A9B4','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (81,'Metallic Green','899B5F','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (82,'Metallic Gold','DBAC34','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (84,'Medium Dark Flesh','CC702A','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (85,'Dark Purple','3F3691','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (86,'Dark Flesh','7C503A','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (89,'Royal Blue','4C61DB','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (92,'Flesh','D09168','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (100,'Light Salmon','FEBABD','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (110,'Violet','4354A3','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (112,'Blue-Violet','6874CA','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (114,'Glitter Trans-Dark Pink','DF6695','t');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (115,'Medium Lime','C7D23C','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (117,'Glitter Trans-Clear','FFFFFF','t');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (118,'Aqua','B3D7D1','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (120,'Light Lime','D9E4A7','f');
INSERT INTO color (`id`,`nombre`,`rgb`,`es_transparente`) VALUES (121,'Deep Blue','05131D','f');
