INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (0,'FLAT TILE 1X2, NO. 180',10);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (1,'Set 0687 Activity Booklet 1',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (2,'Baseplate 16 x 30 with Set 080 Yellow House Print',1);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (3,'Baseplate 16 x 24 with Set 080 Small White House Print',1);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (4,'Baseplate 16 x 24 with Set 080 Red House Print',1);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (5,'Baseplate 16 x 24 with Set 080 Large White House Print',1);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (6,'Homemaker Bookcase 2 x 4 x 4',7);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (7,'Baseplate 24 x 32',2);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (8,'Sticker Sheet #1 for 41055-1',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (9,'Sticker for Set 10019 - (43274/4170393)',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (10,'Sticker for Set 10026 - (44942/4184185)',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (11,'Sticker for Set 10029 - (4216816)',3);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (12,'Sticker for Set 10036 - (821407)',3);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (13,'Pullback Motor 8 x 4 x 2/3',44);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (14,'Minifig Hair Tousled',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (15,'Minifig Shield Broad with Spiked Bottom and Cutout Corner',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (16,'Minifig Shield Broad with Spiked Bottom and Cutout Corner with Handprint Print',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (17,'Minifig Sword [Uruk-hai]',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (18,'Minifig Helmet Castle with Lateral Comb [Uruk-hai]',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (19,'Minifig Helmet Castle with Lateral Comb and Handprint Print',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (20,'Minifig Beard, Rounded End [Gandalf]',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (21,'Minifig Sword Small',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (22,'Minifig Helmet - Rohan Style Castle with Cheek Protection and Horsehead Comb',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (23,'Minifig Helmet - Rohan Style with Cheek Protection, Horsehead Comb and Eomer Print',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (24,'Minifig Helmet - Rohan Cheek Protection and Theoden Print',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (25,'Minifig Hair Long Straight with Elf Ears [Plain]',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (26,'Minifig Hair Long Straight with Light Flesh Elf Ears Print',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (27,'Minifig Helmet Castle with Cheek Protection [Plain]',24);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (28,'Minifig Helmet Castle with Cheek Protection and Dark Red Ornaments Print',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (29,'Body / Head Gollum',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (30,'Body / Head Gollum - Wide Eyes',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (31,'Body / Head Gollum - Narrow Eyes',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (32,'Arm, Bent [Gollum]',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (33,'Arm Goblin King, Left',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (34,'Hand Cave Troll, Left',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (35,'Arm Goblin King, Right',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (36,'Hand Cave Troll, Right',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (37,'Minifig Beard - Full with Braided Moustache Ends',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (38,'Minifig Hair Orc [Plain]',24);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (39,'Minifig Hair Orc with Dark Tan Ears Print',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (40,'Minifig Hair Orc with Olive Green Ears Print',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (41,'Minifig Hair Orc with Medium Dark Flesh Ears Print',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (42,'Paper, Cardboard Backdrop for Set 10075 Spider-Man Action Pack',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (43,'ADULT FIGURE W/HEADSET',4);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (44,'ADULT FIGURE W/HEADSET (Yellow) NO. 6',57);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (45,'Minifig Batman Mask with Angular Ears and Pronounced Brow',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (46,'MASK, BATMAN, NO. 1 with Bat Print',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (47,'Mask Batman with Crack Print',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (48,'Duplo Brick 2 x 10 x 2 Arch with Gold Vines with Leaves and \'C\' in Shield print',4);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (49,'Arm Giant, Right',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (50,'Arm Giant, Right with Blue Darkseid Print',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (51,'Hand Hulk - Right',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (52,'Hand Hulk - Left',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (53,'Sticker for Set 10127 - Sheet 1, Primarily Eastern Teams (47852/4210596)',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (54,'Sticker for Set 10127 - Sheet 2, Primarily Western Teams (47851/4210595)',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (55,'Sticker for Set 10127 - Sheet 3, All 30 Teams and Numbers 1-9 (47853/4210598)',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (56,'Hulk Body [Plain]',24);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (57,'Hulk Body with Dark Tan Pants Print',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (58,'Hulk Body with Dark Purple Pants Print',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (59,'Sticker for Set 10129 - (48074/4214068)',5);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (60,'Sticker for Set 10134 - (48981/4221407)',5);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (61,'Sticker for Set 10144 - (53390/4269558)',6);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (62,'Arm Giant, Left',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (63,'Arm Giant, Left with Blue Darkseid Print',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (64,'Sticker for Set 10159 - (4264102)',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (65,'Minifig Cap, Santa [Plain]',24);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (66,'Minifig Santa Hat with Red Top Print',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (67,'Minifig Helmet Underwater Deep Diver with Trans-Clear Glass',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (68,'Minifig Hair Short Tousled with Headphones Print [Plain]',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (69,'Minifig Hair Short Tousled with Silver Headphones Print',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (70,'Minifig Hair Short Tousled with Black Headphones Print',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (71,'Minifig Hat - Cowboy with Star and Medium Dark Flesh Braid Print',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (72,'Minifig Bag with Handle',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (73,'Pretzel',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (74,'Minifig Trophy Cup Small',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (75,'Minifig Head Cover - Ghost Shroud with Open Mouth',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (76,'RIGHT MINI FIGURE ROBOT LEG',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (77,'Rock 1 x 2 Crystal Stepped',33);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (78,'Rock Stepped with Dark Green Swamp Gas Print',33);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (79,'MOONSTONE NO 1',33);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (80,'Rock Stepped with Gold Egyptian Eye of Horus Print',33);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (81,'Rock Stepped with Black Wolf Print [aka Moonstone]',33);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (82,'Rock Stepped with Black Bat Print',33);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (83,'Rock Stepped with Black Zombie Print',33);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (84,'Rock Stepped with White Lightning Print',33);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (85,'Rock 1 x 2 Crystal Stepped with White Ghost Moonstone Print',33);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (86,'Paper, Certificate of Authenticity for Set 10179 Limited Edition',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (87,'Minifig Wings Fairy',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (88,'Minifig Bladed Claw, Spread',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (89,'Sticker for Set 10187 - (63292/4528621)',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (90,'Sticker for Set 10188 - (64169/453341)',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (91,'Minifig Flipper [Thick]',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (92,'Sticker for Set 10192 - (10192/4528138)',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (93,'ADULT FIG. NO. 1 2012 V2',4);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (94,'Technic Pin Connector Hub with 2 Perpendicular Axles',12);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (95,'Plate 4 X 8',4);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (96,'Bracket 1 x 2 - 1 x 4 [Rounded Corners]',9);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (97,'Tile 6 x 6 with Bottom Tubes',19);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (98,'Sticker for Set 10212 - (88529/4568123)',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (99,'Sticker for Set 10216 - (90051/4582442)',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (100,'Cardboard Game Board - Life of George',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (101,'Sticker for Set 10219',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (102,'Sticker for Set 10220 - Sheet 1 (94347/4614415)',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (103,'Sticker for Set 10220 - Sheet 2 (94349/4614425)',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (104,'Round Sign with 30 Speed Limit Print',4);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (105,'Minifig Head Cover, Swamp Creature with Eye Holes, Fins and Spikes',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (106,'Sticker for Set 10232 - (12949 / 6022692)',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (107,'Sticker for Set 10233 - (12953/6022720)',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (108,'Sticker for Set 10235',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (109,'10240stk01',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (110,'10240stk02',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (111,'10240stk03',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (112,'Plate Special 2 x  2 with 1 Pin Hole [Complete Underside Rib]',9);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (113,'Sticker Sheet for Set 10252 - 26953/6153756 or 26952/6153754',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (114,'Minifig Compound Bow &amp; Arrow',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (115,'Pirate Comic - The Golden Medallion',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (116,'Technic Axle and Pin Connector Triple [120° Offset]',12);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (117,'Minifig Hair with Bat Ears [Plain]',24);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (118,'Minifig Hair with Bat Ears and Medium Dark Flesh Inner Ear Print',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (119,'Minifig Hair with Bat Ears and Dark Bluish Gray Inner Ear Print',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (120,'Minifig Hair with Bat Ears and Tan Inner Ear Print',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (121,'Minifig Head Modified Werewolf [Plain]',24);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (122,'Minifig Head Modified Werewolf',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (123,'Arm with Wing',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (124,'Coffin 2 x 4 x 6 Lid [Plain]',24);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (125,'Coffin 2 x 4 x 6 Lid with White Bat Print [9464 / 9468]',7);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (126,'Coffin 2 x 4 x 6 Lid with Light Bluish Gray Vampire and White Cobwebs Print',7);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (127,'Minifig Helmet with Front Prongs [Plain]',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (128,'Minifig Helmet with Front Prongs and Dark Purple Print (Magneto)',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (129,'Set 1030 Activity Booklet 1 - Parts Tray Organizer Card',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (130,'t 1030 Activity Booklet 10 - Wheels',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (131,'Set 1030 Activity Booklet 11 - Conveyors',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (132,'Set 1030 Activity Booklet 12 - Advanced Gearing',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (133,'Set 1030 Activity Booklet 13 - Pistons',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (134,'Set 1030 Activity Booklet 14 - Merry-go-round',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (135,'Set 1030 Activity Booklet 15 - Cranes',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (136,'Set 1030 Activity Booklet 16 - Lifting with Pulleys',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (137,'Set 1030 Activity Booklet 17 - Water Wheels',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (138,'Set 1030 Activity Booklet 18 - Windmills',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (139,'Set 1030 Activity Booklet 19 - Simple Steering',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (140,'Set 1030 Activity Booklet 2 - Levers',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (141,'Set 1030 Activity Booklet 20 - Advanced Steering',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (142,'Set 1030 Activity Booklet 3 - Supports',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (143,'Set 1030 Activity Booklet 4 - Lifting &amp; Supporting',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (144,'Set 1030 Activity Booklet 5 - Pulleys &amp; Belts',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (145,'Set 1030 Activity Booklet 6 - Gears',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (146,'Set 1030 Activity Booklet 7 - More Gears',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (147,'Set 1030 Activity Booklet 8 - Angles',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (148,'Set 1030 Activity Booklet 9 - Flywheels',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (149,'Windscreen 10 x 6 x 3 Bubble Canopy Double Tapered with Square Front Cutout',47);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (150,'Windscreen 10 x 6 x 3 Bubble Canopy Double Tapered with Square Front Cutout and Light Bluish Gray Jedi Starfighter, Two Red Triangles on Top Print',47);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (151,'Windscreen 10 x 6 x 3 Bubble Canopy Double Tapered with Square Front Cutout and B-wing Starfighter Print',47);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (152,'Windscreen 10 x 6 x 3 Bubble Canopy Double Tapered with Square Front Cutout and Light Bluish Gray Jedi Starfighter, Two Red Triangles on Top Print',47);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (153,'Brick 1 x 4 x 1 1/3 No Studs, Curved Top, with Raised Inside Support',37);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (154,'Set 1032 Activity Booklet 1 - Parts Tray Organizer Card',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (155,'Set 1032 Activity Booklet 10 - Appliances',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (156,'Set 1032 Activity Booklet 11 - Right Angle Drives',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (157,'Set 1032 Activity Booklet 12 - Clamps',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (158,'Set 1032 Activity Booklet 13 - Mixers &amp; Propellers',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (159,'Set 1032 Activity Booklet 14 - Valves &amp; Hammers',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (160,'Set 1032 Activity Booklet 15 - Gearing Down',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (161,'Set 1032 Activity Booklet 16 - Differentials',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (162,'Set 1032 Activity Booklet 17 - Cranes',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (163,'Set 1032 Activity Booklet 18 - Conveyors',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (164,'Set 1032 Activity Booklet 19 - Drawbridges &amp; Boom Gates',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (165,'Set 1032 Activity Booklet 2 - Bracing &amp; Connecting',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (166,'Set 1032 Activity Booklet 20 - Robots',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (167,'Set 1032 Activity Booklet 3 - Using the 4.5V motor',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (168,'Set 1032 Activity Booklet 4 - Wheels &amp; Belts',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (169,'Set 1032 Activity Booklet 5 - Saws',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (170,'Set 1032 Activity Booklet 6 - Small Machinery',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (171,'Set 1032 Activity Booklet 7 - Chains',8);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (172,'Set 1032 Activity Booklet 8 - Chain Drives',8);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (173,'Set 1032 Activity Booklet 9 - Winches',8);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (174,'Arm Cave Troll - Left with Scales Print',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (175,'Arm Cave Troll - Right with Scales Print',13);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (176,'Antenna 6H without Stud Hole',32);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (177,'Duplo Brick 2 x 3 with Curved Top and Eye Print on Both Sides',4);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (178,'Horse, Moveable Legs [Plain]',28);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (179,'Horse, Moveable Legs with Black Bridle and White Blaze Print',28);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (180,'Horse, Moveable Legs with Gray Bridle Print',28);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (181,'Horse, Moveable Legs with Black Bridle and Silver Buckles Print',28);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (182,'Horse, Moveable Legs with Dark Brown Bridle Print',28);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (183,'Horse, Moveable Legs with Gold Bridle and Decorations Print',28);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (184,'Sticker Sheet for 9498-1',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (185,'Minifig Cape Cloth, Narrow with Single Top Hole',27);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (186,'LID FOR FRAME 2X4X2',4);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (187,'Sticker Sheet for 9473-1',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (188,'Sticker for Set 9474 - (10636/6005725)',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (189,'Sticker for Set 10226',17);
INSERT INTO pieza (`num_pieza`,`nombre`,`categoria`) VALUES (190,'Sticker Sheet for 9499-1',17);
