INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (0,'Weetabix Promotional House 1',1976,41);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (1,'Weetabix Promotional House 2',1976,13);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (2,'Weetabix Promotional Windmill',1976,58);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (3,'Special Offer',1985,NULL);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (4,'Weetabix Promotional Lego Village',1976,13);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (5,'Town Mini-Figures',1978,84);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (6,'Castle 2 for 1 Bonus Offer',1987,58);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (7,'Space Mini-Figures',1979,41);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (8,'Space Mini-Figures',1979,13);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (9,'Space Mini-Figures',1979,58);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (10,'Space Mini-Figures',1979,63);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (11,'Castle Mini Figures',1978,32);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (12,'Basic Building set in Cardboard',1965,41);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (13,'Basic Building set in Cardboard',1965,13);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (14,'Basic Building set',1978,84);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (15,'Basic Building set',1968,32);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (16,'Basic Building set',1978,66);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (17,'The Race to Build It Board Game',1999,41);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (18,'Basic Building set',1968,63);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (19,'Basic Building set',1968,97);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (20,'Basic Building set',1968,66);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (21,'Basic Building set',1968,84);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (22,'Basic Building set with Train',1967,13);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (23,'Super set',1969,20);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (24,'Mini-Wheel Model Maker No. 1',1971,58);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (25,'Basic Souvenir Box',1981,63);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (26,'Basic set',1973,32);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (27,'Little House set',1970,78);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (28,'Universal Building set',1976,NULL);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (29,'Locomotive Wheels',1977,20);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (30,'4.5V Motor with Wheels (Small Version)',1966,41);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (31,'4.5V Motor with Wheels (Large Version)',1966,63);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (32,'Guarded Inn',2001,20);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (33,'Metroliner',2001,11);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (34,'Railroad Club Car',2001,11);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (35,'1 x 2 Sand Red Bricks',2001,NULL);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (36,'2 x 2 Sand Red Bricks',2001,NULL);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (37,'2 x 4 Sand Red Bricks',2001,NULL);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (38,'1 x 6 Sand Red Bricks',2001,NULL);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (39,'2 x 4 Sand Red Ridge Roof Tiles Steep Slope',2001,NULL);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (40,'2 x 4 Roof Tile Sand Red',2001,NULL);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (41,'Assorted Blue Bricks',2001,84);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (42,'Assorted Yellow Bricks',2003,41);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (43,'Assorted Blue Plates',2001,58);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (44,'Assorted Yellow Plates',2001,13);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (45,'Open Freight Wagon',2001,32);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (46,'Caboose',2001,54);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (47,'Passenger Wagon',2001,28);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (48,'Tanker',2001,28);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (49,'Hopper Wagon',2001,20);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (50,'Darth Maul',2001,54);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (51,'Rebel Blockade Runner - UCS',2001,13);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (52,'Santa Fe Super Chief, NOT the Limited Edition',2002,6);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (53,'Santa Fe Super Chief, Limited Edition',2002,84);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (54,'U.S.S. Constellation',2003,4);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (55,'Santa Fe Cars - set II (dining, observation, or sleeping car)',2002,20);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (56,'Master Builder set',2002,4);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (57,'Red Baron',2002,54);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (58,'Santa Fe Cars - set I (mail or baggage car)',2002,32);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (59,'Naboo Starfighter - UCS',2002,28);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (60,'Train Engine Shed',2003,54);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (61,'Lunar Lander',2003,32);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (62,'Imperial Star Destroyer - UCS',2002,13);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (63,'Pizza To Go',2002,75);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (64,'Breezeway Cafe',2002,75);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (65,'Black Falcon\'s Fortress',2002,58);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (66,'Black Seas Barracuda',2002,84);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (67,'Main Street, Reissue',2003,85);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (68,'American Flag',2003,20);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (69,'2x2 Electrical Plate',2002,32);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (70,'Windows and Doors',2002,84);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (71,'Pillars and Beams',2002,58);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (72,'Brown Tiles',2002,5);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (73,'Light Gray Arches',2002,84);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (74,'Small Wheels and Axles',2002,58);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (75,'Large Wheels and Axles',2002,63);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (76,'Gray Fences',2002,5);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (77,'Transparent Bricks',2002,54);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (78,'Black Slopes 33',2003,58);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (79,'Black Slopes 33 3 x 2 and 3 x 4',2003,12);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (80,'Black Slopes 33 3 x 1 and 3 x 3',2003,63);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (81,'White Plates 2 x n',2002,12);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (82,'Black Plates 2 x n',2002,28);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (83,'Red Plates 2 x n',2002,12);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (84,'Dark Green Plates 2 x n',2002,32);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (85,'Light Gray Plates 2 x n',2002,32);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (86,'Black Plates 1 x n',2002,54);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (87,'Red Plates 1 x n',2002,54);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (88,'Dark Green Plates 1 x n',2002,12);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (89,'Light Gray Plates 1 x n',2002,12);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (90,'White Plates 1 x n',2002,28);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (91,'Castle Accessories',2002,5);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (92,'Mini-Fig Headgear',2002,5);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (93,'Santa Claus',2002,77);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (94,'Christmas Tree',2002,63);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (95,'Reindeer',2002,84);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (96,'Mr. Bunny',2003,84);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (97,'TECHNIC Beams',2003,84);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (98,'Bushes',2003,64);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (99,'Cross Axles',2003,65);
INSERT INTO `set` (`num_set`,`nombre`,`año`,`tematica`) VALUES (100,'Spider-Man Action Pack',2002,84);
