INSERT INTO tematica (`id`,`nombre`) VALUES (1,'Technic');
INSERT INTO tematica (`id`,`nombre`) VALUES (2,'Arctic Technic');
INSERT INTO tematica (`id`,`nombre`) VALUES (3,'Competition');
INSERT INTO tematica (`id`,`nombre`) VALUES (4,'Expert Builder');
INSERT INTO tematica (`id`,`nombre`) VALUES (5,'Model');
INSERT INTO tematica (`id`,`nombre`) VALUES (6,'Airport');
INSERT INTO tematica (`id`,`nombre`) VALUES (7,'Construction');
INSERT INTO tematica (`id`,`nombre`) VALUES (8,'Farm');
INSERT INTO tematica (`id`,`nombre`) VALUES (9,'Fire');
INSERT INTO tematica (`id`,`nombre`) VALUES (10,'Harbor');
INSERT INTO tematica (`id`,`nombre`) VALUES (11,'Off-Road');
INSERT INTO tematica (`id`,`nombre`) VALUES (12,'Race');
INSERT INTO tematica (`id`,`nombre`) VALUES (13,'Riding Cycle');
INSERT INTO tematica (`id`,`nombre`) VALUES (14,'Robot');
INSERT INTO tematica (`id`,`nombre`) VALUES (15,'Traffic');
INSERT INTO tematica (`id`,`nombre`) VALUES (16,'RoboRiders');
INSERT INTO tematica (`id`,`nombre`) VALUES (17,'Speed Slammers');
INSERT INTO tematica (`id`,`nombre`) VALUES (18,'Star Wars');
INSERT INTO tematica (`id`,`nombre`) VALUES (19,'Supplemental');
INSERT INTO tematica (`id`,`nombre`) VALUES (20,'Throwbot Slizer');
INSERT INTO tematica (`id`,`nombre`) VALUES (21,'Universal Building Set');
INSERT INTO tematica (`id`,`nombre`) VALUES (22,'Creator');
INSERT INTO tematica (`id`,`nombre`) VALUES (23,'Basic Model');
INSERT INTO tematica (`id`,`nombre`) VALUES (24,'Jungle');
INSERT INTO tematica (`id`,`nombre`) VALUES (25,'Castle');
INSERT INTO tematica (`id`,`nombre`) VALUES (26,'The LEGO Batman Movie');
INSERT INTO tematica (`id`,`nombre`) VALUES (27,'Disney');
INSERT INTO tematica (`id`,`nombre`) VALUES (28,'Angry Birds');
INSERT INTO tematica (`id`,`nombre`) VALUES (29,'Train');
INSERT INTO tematica (`id`,`nombre`) VALUES (30,'Scooby-Doo');
INSERT INTO tematica (`id`,`nombre`) VALUES (31,'Creature');
INSERT INTO tematica (`id`,`nombre`) VALUES (32,'Jurassic World');
INSERT INTO tematica (`id`,`nombre`) VALUES (33,'Food & Drink');
INSERT INTO tematica (`id`,`nombre`) VALUES (34,'Building');
INSERT INTO tematica (`id`,`nombre`) VALUES (35,'Cargo');
INSERT INTO tematica (`id`,`nombre`) VALUES (36,'Marvel Super Heroes');
INSERT INTO tematica (`id`,`nombre`) VALUES (37,'Basic Set');
INSERT INTO tematica (`id`,`nombre`) VALUES (38,'Model 2.0');
INSERT INTO tematica (`id`,`nombre`) VALUES (39,'Friends');
INSERT INTO tematica (`id`,`nombre`) VALUES (40,'Minecraft');
INSERT INTO tematica (`id`,`nombre`) VALUES (41,'The Hobbit');
INSERT INTO tematica (`id`,`nombre`) VALUES (42,'The Simpsons');
INSERT INTO tematica (`id`,`nombre`) VALUES (43,'Universe');
INSERT INTO tematica (`id`,`nombre`) VALUES (44,'Recreation');
INSERT INTO tematica (`id`,`nombre`) VALUES (45,'Space');
INSERT INTO tematica (`id`,`nombre`) VALUES (46,'Adventurers');
INSERT INTO tematica (`id`,`nombre`) VALUES (47,'Cars');
INSERT INTO tematica (`id`,`nombre`) VALUES (48,'Spider-Man');
INSERT INTO tematica (`id`,`nombre`) VALUES (49,'Mecha');
INSERT INTO tematica (`id`,`nombre`) VALUES (50,'Town');
INSERT INTO tematica (`id`,`nombre`) VALUES (51,'Arctic');
INSERT INTO tematica (`id`,`nombre`) VALUES (52,'City');
INSERT INTO tematica (`id`,`nombre`) VALUES (53,'Team GB');
INSERT INTO tematica (`id`,`nombre`) VALUES (54,'Dinosaurs');
INSERT INTO tematica (`id`,`nombre`) VALUES (55,'Coast Guard');
INSERT INTO tematica (`id`,`nombre`) VALUES (56,'Superman');
INSERT INTO tematica (`id`,`nombre`) VALUES (57,'X-Men');
INSERT INTO tematica (`id`,`nombre`) VALUES (58,'Batman');
INSERT INTO tematica (`id`,`nombre`) VALUES (59,'Sports');
INSERT INTO tematica (`id`,`nombre`) VALUES (60,'Hospital');
INSERT INTO tematica (`id`,`nombre`) VALUES (61,'Police');
INSERT INTO tematica (`id`,`nombre`) VALUES (62,'Western');
INSERT INTO tematica (`id`,`nombre`) VALUES (63,'Pirates');
INSERT INTO tematica (`id`,`nombre`) VALUES (64,'Holiday');
INSERT INTO tematica (`id`,`nombre`) VALUES (65,'Rock Raiders');
INSERT INTO tematica (`id`,`nombre`) VALUES (66,'Trains');
INSERT INTO tematica (`id`,`nombre`) VALUES (67,'Classic Town');
INSERT INTO tematica (`id`,`nombre`) VALUES (68,'Halloween');
INSERT INTO tematica (`id`,`nombre`) VALUES (69,'Discovery');
INSERT INTO tematica (`id`,`nombre`) VALUES (70,'Vikings');
INSERT INTO tematica (`id`,`nombre`) VALUES (71,'Cowboys');
INSERT INTO tematica (`id`,`nombre`) VALUES (72,'Indians');
INSERT INTO tematica (`id`,`nombre`) VALUES (73,'Speedorz');
INSERT INTO tematica (`id`,`nombre`) VALUES (74,'Speed Champions');
INSERT INTO tematica (`id`,`nombre`) VALUES (75,'Fantasy');
INSERT INTO tematica (`id`,`nombre`) VALUES (76,'Station');
INSERT INTO tematica (`id`,`nombre`) VALUES (77,'Elves');
INSERT INTO tematica (`id`,`nombre`) VALUES (78,'Ghostbusters');
INSERT INTO tematica (`id`,`nombre`) VALUES (79,'Avatar');
INSERT INTO tematica (`id`,`nombre`) VALUES (80,'Desert');
INSERT INTO tematica (`id`,`nombre`) VALUES (81,'Post Office');
INSERT INTO tematica (`id`,`nombre`) VALUES (82,'Mosaic');
INSERT INTO tematica (`id`,`nombre`) VALUES (83,'Star Wars Universe');
INSERT INTO tematica (`id`,`nombre`) VALUES (84,'Skylines');
INSERT INTO tematica (`id`,`nombre`) VALUES (85,'Christmas');
INSERT INTO tematica (`id`,`nombre`) VALUES (86,'Divers');
INSERT INTO tematica (`id`,`nombre`) VALUES (87,'Extreme Team');
INSERT INTO tematica (`id`,`nombre`) VALUES (88,'Launch Command');
INSERT INTO tematica (`id`,`nombre`) VALUES (89,'Outback');
INSERT INTO tematica (`id`,`nombre`) VALUES (90,'Paradisa');
INSERT INTO tematica (`id`,`nombre`) VALUES (91,'Seasonal');
INSERT INTO tematica (`id`,`nombre`) VALUES (92,'Res-Q');
INSERT INTO tematica (`id`,`nombre`) VALUES (93,'Space Port');
INSERT INTO tematica (`id`,`nombre`) VALUES (94,'Town Jr.');
INSERT INTO tematica (`id`,`nombre`) VALUES (95,'Indiana Jones');
INSERT INTO tematica (`id`,`nombre`) VALUES (96,'Forestmen');
INSERT INTO tematica (`id`,`nombre`) VALUES (97,'Avengers');
INSERT INTO tematica (`id`,`nombre`) VALUES (98,'UFO');
INSERT INTO tematica (`id`,`nombre`) VALUES (99,'Gas Station');
INSERT INTO tematica (`id`,`nombre`) VALUES (100,'Dino Island');
